# Generated by Django 3.2.6 on 2021-09-22 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0002_studentuserprofile_teacheruserprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacheruserprofile',
            name='teachers_profile',
        ),
        migrations.DeleteModel(
            name='StudentUserProfile',
        ),
        migrations.DeleteModel(
            name='TeacherUserProfile',
        ),
    ]
