# Generated by Django 3.2.6 on 2021-09-22 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0003_auto_20210922_0503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_img',
            field=models.ImageField(default='images/avatar1.png', upload_to='images/'),
        ),
    ]
